check-for-app-update: false
search:
  scope: "all-layers"
fail-on-severity: 'high'
# vulnerabilities which doesn't affect the image
ignore:
  # we don't use zlib in the container at all
  - vulnerability: CVE-2022-37434

