version: 2.1
commands:
  build_app:
    parameters:
      push:
        type: boolean
        default: true
      audit:
        type: boolean
        default: true
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install grype for audit
          command: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin v0.38.0
      - run:
          name: Building Docker Image
          command: docker build -t elasticio/api-docs:${CIRCLE_SHA1} .
      - when:
          condition: << parameters.audit >>
          steps:
            - run:
                name: Auditing Docker image
                working_directory: ~/project
                command: grype -q -c .grype.yaml elasticio/api-docs:${CIRCLE_SHA1}
      - when:
          condition: << parameters.push >>
          steps:
            - run:
                name: Logging in into Docker Hub
                command: docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
            - run:
                name: Pushing Revisioned Docker Image
                command: docker push elasticio/api-docs:${CIRCLE_SHA1}
            - run:
                name: Pushing Branched Docker Image
                command: docker push elasticio/api-docs:${CIRCLE_BRANCH}
jobs:
  build-docker-image:
    parameters:
      push:
        type: boolean
        default: true
      audit:
        type: boolean
        default: true
    docker:
      - image: circleci/node:8-stretch
    steps:
      - build_app:
          push: << parameters.push >>
          audit: << parameters.audit >>
  tag_release:
    working_directory: ~/api-docs
    docker:
      - image: circleci/node:12.19.1-stretch
    steps:
      - checkout:
          path: ~/api-docs
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7
      - run:
          name: Tag release images
          command: ~/api-docs/.circleci/tag_release.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-docker-image
  tag_docker:
    jobs:
      - tag_release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]{2}\.[0-9]{2}(\.[0-9]+)?$/
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-docker-image:
          push: false
