version: 2
jobs:
    build-and-push-docker-image:
        docker:
            - image: circleci/node:8-stretch
        steps:
            - checkout
            - setup_remote_docker:
                  version: 20.10.7
            - run:
                  name: Building Docker Image
                  command: docker build -t elasticio/api-docs:${CIRCLE_SHA1} .
            - run:
                  name: Tagging Docker Images
                  command: docker tag elasticio/api-docs:${CIRCLE_SHA1} elasticio/api-docs:${CIRCLE_BRANCH}
            - run:
                  name: Logging in into Docker Hub
                  command: docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
            - run:
                  name: Pushing Revisioned Docker Image
                  command: docker push elasticio/api-docs:${CIRCLE_SHA1}
            - run:
                  name: Pushing Branched Docker Image
                  command: docker push elasticio/api-docs:${CIRCLE_BRANCH}
    tag_release:
        working_directory: ~/api-docs
        docker:
            - image: circleci/node:12.19.1-stretch
        steps:
            - checkout:
                  path: ~/api-docs
            - setup_remote_docker:
                  docker_layer_caching: true
                  version: 20.10.7
            - run:
                  name: Tag release images
                  command: ~/api-docs/.circleci/tag_release.sh
workflows:
    version: 2
    build_and_test:
        jobs:
            - build-and-push-docker-image
    tag_docker:
        jobs:
            - tag_release:
                  filters:
                      branches:
                          ignore: /.*/
                      tags:
                          only: /^[0-9]{2}\.[0-9]{2}(\.[0-9]+)?$/
